# Project information
site_name: Data n Storage Refresher
site_url: https://arcelopera.github.io/datanstorage
site_description: Data n Storage refresher.
site_author: ArceLopera

# Repository
repo_url: https://github.com/ArceLopera/datanstorage
repo_name: ArceLopera/datanstorage
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright &copy; 2025

# Social media
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carlos-arcelopera
    - icon: fontawesome/brands/github
      link: https://github.com/ArceLopera
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/solid/paper-plane
      link: mailto:arcelopera.carlos@gmail.com

# Configuration
theme:
  name: material
  logo: #Images/Elephpant.svg
  #<a href="https://iconscout.com/icons/elephant" class="text-underline font-size-sm" target="_blank">Elephant</a> by <a href="https://iconscout.com/contributors/yogiaprelliyanto" class="text-underline font-size-sm" target="_blank">Yaprativa</a>
  favicon: #Images/elephant.ico
  palette:
    
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search


# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Basic: 
      - General: db/db_basic.md
      - SQL: 
          - General: db/sql/db_sql.md
          - Install: 
              - General: db/sql/db_sqlinstall.md
              - ODBC: db/sql/db_odbc.md
              - SQLite 🛢️: db/sql/db_sqlite.md
              - MySQL🐬: db/sql/db_mysql.md
              - PostgreSQL🐘: db/sql/db_postgresql.md
          - Basic:
              - Basic SQL Commands: db/sql/db_sqlbasic.md
              - JOIN: db/sql/db_sqljoin.md
          - Advanced:
              - Subqueries: db/sql/db_sqlsubquery.md
              - Index: db/sql/db_sqlindex.md
              - ACID: db/sql/db_sqlacid.md
              - Various: db/sql/db_sqladv2.md
              - More: db/sql/db_sqlproc.md
      - NoSQL:
          - Redis🔥: db/nosql/db_redis.md
  - Ai:
      - Frameworks: ai_frameworks.md 
